# Generated by Django 3.1.1 on 2020-12-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20201205_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
